// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nkfdonvsouezpxbgukco.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5rZmRvbnZzb3VlenB4Ymd1a2NvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODM0NDkxNzgsImV4cCI6MjA5OTAyNTE3OH0.eM_l1J4q4S5u6Pbn9IrumAt213xLjR-h6whOuZwGh0Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});